#!/bin/sh

export LC_ALL=C

#
# Generates full list of posts in chronological order
#

echo "<ul>"
	for f in ./blog/*.md ; do
		d=$($ZS var $f date)
		if [ ! -z $d ] ; then
			timestamp=`date --date "$d" +%s`
			url=`$ZS var $f url`
			title=`$ZS var $f title | tr A-Z a-z`
			descr=`$ZS var $f description`
			echo "$timestamp <li><a href=\"$url\">$title</a> - $(date "+%B %d, %Y" --date @$timestamp)</li>"
		fi
	done | sort -r -n | cut -d' ' -f2-
echo "</ul>"
