#!/bin/sh

TITLE="zserge's blog"
BASEURL="http://zserge.com"

xml=$(cat << EOF
<?xml version="1.0"?>
<rss version="2.0">
<channel>
<title>$TITLE</title>
<link>$BASEURL/blog.html</link>
<description>My thoughts on software, simplicity and how to make it work together</description>
<language>en-us</language>
<pubDate>$(date -R)</pubDate>
<lastBuildDate>$(date -R)</lastBuildDate>
	$(find -name '*.md' -type f | while read line ; do
		timestamp=$($ZS var $line date)
		if [ ! -z $timestamp ] ; then
			echo $(date --date $timestamp +%s) $line
		fi
	done | sort -r -n | cut -d' ' -f2 | while read f; do
		url=$($ZS var $f url)
		timestamp=$(date --date $($ZS var $f date) +%s)
		name=$($ZS var $f title)
		desc=$($ZS var $f description)
		printf "<item><title>%s</title><link>%s</link><description>%s</description><pubDate>%s</pubDate><guid>%s</guid></item>\n" \
			"$name" "$BASEURL/$url" "$desc" "$(date --date @$timestamp -R)" "$BASEURL/$url"
	done)
</channel>
</rss>
EOF
)
echo "$xml" > $ZS_OUTDIR/rss.xml
